"""Initial migration

Revision ID: 417bdda91b5b
Revises: 
Create Date: 2023-11-29 17:58:02.075678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '417bdda91b5b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('star_rating', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('search_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('search_query', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('categories_groups')
    op.drop_table('categories')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NullType(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('name',
               existing_type=sa.NullType(),
               nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.NullType(),
               nullable=False)
        batch_op.drop_column('image_url')
        batch_op.drop_column('base_cost')
        batch_op.drop_column('category')
        batch_op.drop_column('category_id')

    with op.batch_alter_table('vendor_products', schema=None) as batch_op:
        batch_op.alter_column('vendor_id',
               existing_type=sa.NullType(),
               nullable=False)
        batch_op.alter_column('product_id',
               existing_type=sa.NullType(),
               nullable=False)
        batch_op.create_foreign_key(None, 'vendors', ['vendor_id'], ['id'])
        batch_op.create_foreign_key(None, 'products', ['product_id'], ['id'])
        batch_op.drop_column('id')
        batch_op.drop_column('international_shipping')

    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NullType(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('name',
               existing_type=sa.NullType(),
               nullable=False)
        batch_op.drop_column('website')
        batch_op.drop_column('description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.NullType(), nullable=True))
        batch_op.add_column(sa.Column('website', sa.NullType(), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.NullType(),
               nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.NullType(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('vendor_products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('international_shipping', sa.NullType(), nullable=True))
        batch_op.add_column(sa.Column('id', sa.NullType(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('product_id',
               existing_type=sa.NullType(),
               nullable=True)
        batch_op.alter_column('vendor_id',
               existing_type=sa.NullType(),
               nullable=True)

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.NullType(), nullable=True))
        batch_op.add_column(sa.Column('category', sa.NullType(), nullable=True))
        batch_op.add_column(sa.Column('base_cost', sa.NullType(), nullable=True))
        batch_op.add_column(sa.Column('image_url', sa.NullType(), nullable=True))
        batch_op.alter_column('description',
               existing_type=sa.NullType(),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.NullType(),
               nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.NullType(),
               nullable=True,
               autoincrement=True)

    op.create_table('categories',
    sa.Column('id', sa.NullType(), nullable=True),
    sa.Column('name', sa.NullType(), nullable=True),
    sa.Column('description', sa.NullType(), nullable=True),
    sa.Column('group_id', sa.NullType(), nullable=True)
    )
    op.create_table('categories_groups',
    sa.Column('id', sa.NullType(), nullable=True),
    sa.Column('name', sa.NullType(), nullable=True),
    sa.Column('description', sa.NullType(), nullable=True)
    )
    op.drop_table('search_history')
    op.drop_table('reviews')
    op.drop_table('users')
    # ### end Alembic commands ###
