"""add id to vendor_products

Revision ID: 67dcde05d4bc
Revises: 6bb50a91429c
Create Date: 2023-11-30 01:23:58.027268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67dcde05d4bc'
down_revision = '6bb50a91429c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendor_products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendor_products', schema=None) as batch_op:
        batch_op.drop_column('id')

    # ### end Alembic commands ###
