"""add id column

Revision ID: 961377968cb6
Revises: ff8e05fd3182
Create Date: 2023-11-30 20:20:14.244228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '961377968cb6'
down_revision = 'ff8e05fd3182'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendor_products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendor_products', schema=None) as batch_op:
        batch_op.drop_column('id')

    # ### end Alembic commands ###
